W4D5/music-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands
  resources :albums
end

W4D5/music-app/app/models/album.rb
class Album < ApplicationRecord
end

W4D5/music-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W4D5/music-app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
  
end

W4D5/music-app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  after_initialize :ensure_session_token

  attr_reader :password
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def generate_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
  end

  def password= (password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email)
    user && user.is_password?(password) ? user : nil
  end


end

W4D5/music-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    redirect_to new_session_url if current_user.nil?
  end
end

W4D5/music-app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.find_by(name: params[:band][:name])
    if @band
      flash.now[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    else
      @band = Band.create(name: params[:band][:name])
      redirect_to bands_url
    end

  end


  def show
    @band = Band.find(params[:id])
    render :show
  end


  def edit
    @band = Band.find(params[:id])
    render :edit
  end


  def update
    @band = Band.find(params[:id])
    if @band
      @band.update_attributes(name: params[:band][:name])
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  protected

  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5/music-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user.nil?
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    elsif !user.activated?
      flash.now[:errors] = ['You must activate your account first! Check your email.']
      render :new
    else
      log_in_user!(user)
      redirect_to root_url
    end
  end

  def destroy
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

W4D5/music-app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render :new
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def activate
    @user = User.find_by_activation_token(params[:activation_token])
    @user.activate!
    login_user!(@user)
    flash[:notice] = 'Successfully activated your account!'
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/music-app/app/helpers/application_helper.rb
module ApplicationHelper
end

W4D5/music-app/app/helpers/bands_helper.rb
module BandsHelper
end

W4D5/music-app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W4D5/music-app/app/helpers/users_helper.rb
module UsersHelper
end

W4D5/music-app/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form class="form" action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%=http_method%>">
  <input type="hidden"
         name="authenticity_token"
         value="form_authenticity_token">

  <label for="band-name">Band Name: </label>
  <input id = "new-band-name" type="text" name="band[name]" value=" <%= band.name %> ">
  <br>
  <input type="submit">
</form>

W4D5/music-app/app/views/bands/edit.html.erb
<p>Update Profile For: <%= @band.name %> </p>
<%= render 'form', band: @band %>

W4D5/music-app/app/views/bands/index.html.erb
<p>Current Bands:</p>

<% @bands.each do |band| %>
  <p><%= band.name %> </p>
<% end %>

W4D5/music-app/app/views/bands/new.html.erb
<p>Add A New Band: </p>
<%= render "form", band: @band %>

W4D5/music-app/app/views/bands/show.html.erb
<p>Band: </p>
<%= @band.name %>

W4D5/music-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>Music App</h1>
    <%= yield %>
  </body>
</html>

W4D5/music-app/app/views/users/new.html.erb
<p>New User</p>


<form class="form" action="<%=new_user_url%>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="form_authenticity_token">
  <label for="new-user-email">Email</label>
  <input id = "new-user-email" type="text" name="user[email]">
  <br>
  <label for="new-user-password">Password</label>
  <input id = "new-user-password" type="password" name="user[password]">
  <br>
  <input type="submit">
</form>

W4D5/music-app/app/views/users/show.html.erb
<h1 class='page-header'>User Profile</h1>

<p>  Email: <%= @current_user.email %> </p>